### ISSUE TITLE
empty object list creates error message

### ISSUE THREAD

**Issue by miriki** [eklam/VbsJson#2]
The block

            idx = SkipWhitespace(str, idx)
            c = Mid(str, idx, 1)
            If c = "}" Then
                Exit Do
            ElseIf c <> "," Then
                Err.Raise 8732,,"Expecting , delimiter"
            End If

raises the error with a string containing [] as an empty list.

I got this error with a web requst from tmdb at index 1055 and the string +/- 20 characters around that is:
],"person_results":[],"tv_results":[],"tv
The closing ] directly after the opening [ is unexpected

Greetings, Michael

**Comment by wqweto** [comment]
There is a pending pull request #1 that fixes this issue.

**Comment by informas** [comment]
I tried these changes and it apparently works..., at least ignore the error... 

            idx = SkipWhitespace(str, idx)
            c = Mid(str, idx, 1)
            If c = "}" Then
                Exit Do

            'To accept empty objects without error            
            ElseIf c = "]" Then
                Exit Do


            ElseIf c <> "," Then
                Err.Raise 8732,,"Expecting , delimiter"
            End If

Best regards.

Jorge Colaccini

**Comment by wqweto** [comment]
@informas: For correct fix please check out Pull Request #1

The problems stems from [just 2 lines of code missing](https://github.com/eklam/VbsJson/pull/1/files) with index increment on closing brackets both for arrays and objects.

**Comment by RenanStigliani** [comment]
Hi @wqweto finally merger your PR.
Cheers!

**Comment by informas** [comment]
Thanks Vladimir

Best regards.

Jorge Colaccini

----- Original Message -----
